[project]
name = "bq-caapi-ge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "google-adk>=1.23.0",
    "google-auth>=2.48.0",
    "google-cloud-geminidataanalytics>=0.9.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
